name: Terraform auto format
on:
  push:
    branches:
      - 'feature/**'
jobs:
  AutoFormat:
    name: auto format
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Get Terraform Version
        id: tf_version
        run: |
          echo "value=$(cat .terraform-version)" >> $GITHUB_OUTPUT
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.tf_version.outputs.value }}
      - name: terraform fmt check
        id: fmt-check
        run: terraform fmt -recursive -check
        continue-on-error: true
      # fmt check で対象ファイルが見つかった時だけ以下の処理でfmtしそれをコミットする。
      - name: terraform fmt
        if: steps.fmt-check.outcome == 'failure'
        run: terraform fmt -recursive
      - name: auto commit
        if: steps.fmt-check.outcome == 'failure'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: terraform fmt auto commit