name: create or update pull request
on:
  push:
    branches:
      - "feature/**"
jobs:
  CreatePullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Reset promotion branch
        run: |
          git fetch origin ${{ github.ref_name }}:${{ github.ref_name }}
          git reset --hard ${{ github.ref_name }}
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          # github app tokenを使用しているのはこの処理中に発生したイベントで他のworkflow(prのイベント起点)を走らせたいから。Github Tokenを使用するとGithub Actionsの仕様上、PRのイベントを取れない。PATでも代用可能だが一々ローテート必須なのは個人的に論外。
          # 参考：https://github.com/peter-evans/create-pull-request/issues/48
          token: ${{ steps.create_token.outputs.token }}
          branch: ${{ github.ref_name }}
          title: main <- ${{ github.ref_name }}
          body: |
            ## プルリクエストとそのレビュー、CICD処理などについて
            [Github Wiki参照](https://github.com/rice01010101/terraform_basecode/wiki/07_%E3%83%97%E3%83%AB%E3%83%AA%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%88%E3%81%A8%E3%81%9D%E3%81%AE%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC%E3%80%81CICD%E5%87%A6%E7%90%86%E3%81%AA%E3%81%A9%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)
            理解していれば都度確認する必要はない。
            
            ## PR内リンク（コメントが存在しない場合は遷移しない）
            ### AWS
            #### Dev環境
            - [terraform init](#terraform-init-aws/environments/dev)
            - [terraform validate](#terraform-validate-aws/environments/dev)
            - [terraform plan](#terraform-plan-aws/environments/dev)
            - [trivy](#trivy-result-aws/environments/dev)

          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "1"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: auto labeling
        id: labeling
        uses: actions/labeler@v5
        with:
          pr-number: ${{ steps.cpr.outputs.pull-request-number }}
          sync-labels: true
          configuration-path: .github/labeler.yml
