name: review by reviewdog, using tflint and trivy.
on:
  pull_request:
    types: [opened, edited, synchronize, labeled, unlabeled]
jobs:
  get_pr_label:
    uses: ./.github/workflows/get-pullrequest-label.yml
    with:
      pr_number: ${{ github.event.number }}
  tflint:
    runs-on: ubuntu-latest
    needs: get_pr_label
    strategy:
      matrix:
        envs: ${{ fromJson(needs.get_pr_label.outputs.pr_labels) }} # Array(string)はそのままだとmatrixのinputになれないためjson変換を行っている
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: tflint
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tflint_init: true
          tflint_config: ${{ github.workspace }}/.tflint.hcl
          tflint_target_dir: "${{ matrix.envs }}"
          filter_mode: "nofilter" # target_dir配下は変更の有無などを問わず全てチェックする
          reporter: github-pr-review
      - name: trivy
        uses: reviewdog/action-trivy@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          trivy_command: config # terraform config
          trivy_target: "${{ matrix.envs }}"
          trivy_version: latest
          filter_mode: "nofilter"
          flags: -tee
          reporter: github-pr-review
      - name: Get Terraform Version
        id: tf_version
        # .terraform-versionから使用するバージョンを自動取得・設定
        run: |
          echo "value=$(cat .terraform-version)" >> $GITHUB_OUTPUT
      - name: tfvalidate
        uses: reviewdog/action-terraform-validate@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          terraform_version: ${{ steps.tf_version.outputs.value }}
          workdir: "${{ matrix.envs }}"
          level: warning
          filter_mode: "nofilter"
          reporter: github-pr-review