name: pragent review using openai gpt
on:
  issue_comment:
    types: [created, edited]
jobs:
  pr_agent_job:
    name: Run pr agent on every pull request, respond to user comments
    # run only pullrequest and user comment
    if: ${{ github.event.sender.type != 'Bot' && github.event.issue.pull_request}}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: 'Japanese only'
          PR_REVIEWER.EXTRA_INSTRUCTIONS: 'Japanese only'
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: 'Japanese only'